inherit:
    - counterfactual.yaml

model:
    family: "gpt2_sde"
    n_embd: 256
    n_positions: 60

training:
    batch_size: 8
    data: "sde"
    train_steps: 50000
    diversity: 2000000
    save_every_steps: 40000
    # learning_rate: 0.0001
    lamb: 40
    max_time: .5
    curriculum:
        vars:           # curriculum learning on DAG complexity
            start: 2    # binary DAG
            end: 2
            inc: 1
            interval: 8000

wandb:
    name: "sde"